let cs=[],price=1.1,timer=null,ct=null,deadline=0;
let st=JSON.parse(localStorage.qsb2||'{"t":0,"w":0,"l":0,"s":0,"sum":0,"p":0,"gw":0,"gl":0}'),hist=JSON.parse(localStorage.qsh2||"[]");
const $=x=>document.getElementById(x);
function rn(){let u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function candle(){let o=price,c=Math.max(.00001,o+(Math.random()-.49)*.0007+rn()*.00025),h=Math.max(o,c)+Math.random()*.00018,l=Math.min(o,c)-Math.random()*.00018;price=c;return{o,h,l,c}}
function sma(a,n){return a.length<n?null:a.slice(-n).reduce((x,y)=>x+y,0)/n}
function ema(a,n){if(a.length<n)return null;let k=2/(n+1),e=a.slice(0,n).reduce((x,y)=>x+y,0)/n;for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];d>=0?g+=d:l-=d}if(!l)return 100;let q=(g/n)/(l/n);return 100-100/(1+q)}
function macd(a){let x=ema(a,12),y=ema(a,26);return x==null||y==null?null:x-y}
function analyze(a=cs.map(x=>x.c),last=cs.at(-1)){let f=sma(a,9),s=sma(a,21),r=rsi(a),m=macd(a),call=0,put=0,w=[];if(f&&s){if(f>s){call+=25;w.push("9/21 bullish")}else{put+=25;w.push("9/21 bearish")}}if(r!=null){if(r>=52&&r<=68){call+=20;w.push("RSI bullish")}else if(r<=48&&r>=32){put+=20;w.push("RSI bearish")}}if(m!=null){if(m>0){call+=20;w.push("MACD positive")}else{put+=20;w.push("MACD negative")}}if(last){let b=last.c-last.o;if(b>0)call+=10;if(b<0)put+=10}let best=Math.max(call,put),sec=Math.min(call,put),co=Math.min(99,50+Math.round(best*.45)+Math.round((best-sec)*.25)),d="WAIT";if(co>=+$("th").value&&best>=45&&best-sec>=15)d=call>put?"CALL":"PUT";let z=a.slice(-30);return{d,co,p:a.at(-1),r,m,t:f&&s?(f>s?"BULLISH":"BEARISH"):"UNKNOWN",sup:Math.min(...z),res:Math.max(...z),w:w.join("; ")}}
function render(x){$("dir").textContent=x.d;$("dir").className=x.d==="CALL"?"call":x.d==="PUT"?"put":"wait";$("conf").textContent="Confidence "+x.co+"%";$("why").textContent=x.w||"No strong setup.";$("price").textContent=x.p?.toFixed(5)||"--";$("rsi").textContent=x.r?.toFixed(1)||"--";$("macd").textContent=x.m?.toFixed(6)||"--";$("trend").textContent=x.t;$("sup").textContent=x.sup?.toFixed(5)||"--";$("res").textContent=x.res?.toFixed(5)||"--"}
function save(){localStorage.qsb2=JSON.stringify(st);localStorage.qsh2=JSON.stringify(hist)}
function draw(){let wr=st.t?st.w/st.t*100:0,pf=st.gl?st.gw/st.gl:0;$("total").textContent=st.t;$("wins").textContent=st.w;$("losses").textContent=st.l;$("wr").textContent=st.t?wr.toFixed(1)+"%":"--";$("avg").textContent=st.t?(st.sum/st.t).toFixed(1)+"%":"--";$("streak").textContent=st.s;$("dd").textContent=Math.max(0,-st.p).toFixed(2);$("pf").textContent=pf?pf.toFixed(2):"--";$("history").innerHTML=hist.slice(0,30).map(x=>`<div class="item"><span>${x.time} • ${x.d} • ${x.co}%</span><b class="${x.r==="WIN"?"win":"loss"}">${x.r}</b></div>`).join("")}
function tick(){cs.push(candle());if(cs.length>300)cs.shift();let x=analyze();render(x);deadline=Date.now()+(+$("tf").value)*60000;if(x.d!=="WAIT")setTimeout(()=>{let before=price,n=candle(),win=x.d==="CALL"?n.c>before:n.c<before;st.t++;st.sum+=x.co;if(win){st.w++;st.s=0;st.p++;st.gw++}else{st.l++;st.s++;st.p--;st.gl++}hist.unshift({time:new Date().toLocaleTimeString(),d:x.d,co:x.co,r:win?"WIN":"LOSS"});save();draw()},900)}
$("th").oninput=()=>$("tv").textContent=$("th").value+"%";$("start").onclick=()=>{if(timer)return;tick();timer=setInterval(tick,6000);ct=setInterval(()=>{$("count").textContent="Next candle: "+Math.ceil(Math.max(0,deadline-Date.now())/1000)+"s"},250)};$("stop").onclick=()=>{clearInterval(timer);clearInterval(ct);timer=ct=null;$("dir").textContent="WAIT";$("dir").className="wait"};$("reset").onclick=()=>{st={t:0,w:0,l:0,s:0,sum:0,p:0,gw:0,gl:0};hist=[];save();draw()};$("notify").onclick=async()=>{"Notification"in window&&await Notification.requestPermission()};
$("backtest").onclick=async()=>{let f=$("csv").files[0];if(!f){$("out").textContent="Select a CSV first.";return}let ls=(await f.text()).trim().split(/\r?\n/),a=[];for(let i=1;i<ls.length;i++){let p=ls[i].split(",").map(Number);if(p.length>=5&&!p.slice(1,5).some(Number.isNaN))a.push({o:p[1],h:p[2],l:p[3],c:p[4]})}if(a.length<60){$("out").textContent="Need at least 60 valid OHLC rows.";return}let w=0,l=0,n=0;for(let i=40;i<a.length-1;i++){let x=analyze(a.slice(0,i+1).map(q=>q.c),a[i]);if(x.d==="WAIT")continue;n++;let ok=x.d==="CALL"?a[i+1].c>a[i].c:a[i+1].c<a[i].c;ok?w++:l++}$("out").textContent=`Rows: ${a.length}\nSignals: ${n}\nWins: ${w}\nLosses: ${l}\nWin rate: ${n?(w/n*100).toFixed(2):"0"}%\n\nHistorical simulation only.`};
while(cs.length<150)cs.push(candle());draw();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});